  "name": "application",
  "propertySources": [{
    "source": {
      "projet": "Banking_projet",
      "classe": "MATER PRO 2026",
      "filiere": "Informatique",
      "semestre": "2",
      "professeur": "Soufayanou njiasse",
      "heure": "19:00"    }
