spring.application.name=service-config
server.port=8080

# ✅ URL de votre dépôt GitHub
spring.cloud.config.server.git.uri=https://github.com/soufayanounjiasse/Banking_projet

# ✅ Branche principale
spring.cloud.config.server.git.default-label=main

# ✅ Dossier des fichiers de config (votre dossier cloud_config_conf)
spring.cloud.config.server.git.search-paths=cloud_config_conf

# ✅ Cloner dès le démarrage (évite les erreurs au 1er appel)
spring.cloud.config.server.git.clone-on-start=true

# ✅ Forcer le refresh depuis GitHub (pas de cache local)
spring.cloud.config.server.git.force-pull=true